import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[window]

title = "alacritty"
dynamic_title = false
padding = { x = 10, y = 10 }
dynamic_padding = true

[mouse]

hide_when_typing = true

[keyboard]
bindings = [
{key = "Y", mods = "Control", action = "PasteSelection"}
]

[shell]
program = "/usr/bin/zsh"
args = ["-l"]
