import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetbrainsMono Nerd Font"

[window.padding]
x = 10
y = 4

[window]

title = "alacritty"
dynamic_title = true 
dynamic_padding = true
blur = true
opacity = 1

[mouse]

hide_when_typing = true

[keyboard]
bindings = [
{key = "Y", mods = "Control", action = "PasteSelection"}
]

[shell]
program = "/usr/bin/zsh"
args = ["-l"]
