import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[window]

title = "alacritty"
dynamic_title = false
dynamic_padding = true
blur = true
opacity = 0.8

[mouse]

hide_when_typing = true

[keyboard]
bindings = [
{key = "Y", mods = "Control", action = "PasteSelection"}
]

[shell]
program = "/usr/bin/zsh"
args = ["-l"]
